version: "3"
services:
  tempo:
    image: grafana/tempo:latest
    command: [-config.file=/etc/tempo.yaml]
    volumes:
      - ./infra/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    # ports:
      # - "14268:14268" # jaeger ingest
      # - "3200:3200" # tempo
      # - "9095:9095" # tempo grpc
      # - "4317:4317" # otlp grpc
      # - "4318:4318" # otlp http
      # - "9411:9411" # zipkin

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./infra/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./infra/collector.yaml:/etc/otel-collector-config.yaml
    ports:
      # - "1888:1888"   # pprof extension
      # - "13133:13133" # health check extension
      # - "55679:55679" # zpages extension
      # - "4317:4317"   # otlp grpc receiver
      # - "8888:8888"   # prometheus metrics exposed by the collector
      - "4318:4318"   # otlp http receiver
      - "8889:8889"   # prometheus exporter metrics

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./infra/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./infra/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./infra/dashboards:/var/lib/grafana/dashboards

    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/hackernews.json
    ports:
      - "3030:3000"

volumes:
  tempo-data:
