global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # - job_name: prometheus
  #   static_configs:
  #     - targets: [prometheus:9090] # metrics from the prometheus application
  # - job_name: tempo
  #   static_configs:
  #     - targets: [tempo:3200] # metrics from the tempo application
  - job_name: collector
    static_configs:
      - targets: [collector:8889] # metrics from the application
      # - targets: [collector:8888] # metrics exported by the collector itself
