{
 "title": "HackerNews",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "a54dc36c", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Fetch Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(hackernews_fetch_success_count[$__rate_interval])",
     "legendFormat": "Fetch Rate"
    }
   ]
  },
  {
   "title": "Fetch Success Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "hackernews_fetch_success_count", "legendFormat": "Fetch Count" }
   ]
  },
  {
   "title": "Fetch Timer",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(hackernews_fetch_timer_milliseconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}